// const movies = [
//     {
//       name: "The Dark Knight",
//       title: "The Dark Knight",
//       language: "English",
//       imdbRating: 9.0,
//       photoLink: "https://example.com/darkknight.jpg",
//       review: "A masterful superhero film with intense performances.",
//       launchDate: "2008-07-18",
//       genre: "Action, Crime, Drama",
//       director: "Christopher Nolan",
//       cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"]
//     },
//     {
//       name: "Inception",
//       title: "Inception",
//       language: "English",
//       imdbRating: 8.8,
//       photoLink: "https://example.com/inception.jpg",
//       review: "A visually stunning and intellectually stimulating heist film.",
//       launchDate: "2010-07-16",
//       genre: "Action, Adventure, Sci-Fi",
//       director: "Christopher Nolan",
//       cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"]
//     },
//     {
//       name: "Parasite",
//       title: "Gisaengchung",
//       language: "Korean",
//       imdbRating: 8.6,
//       photoLink: "https://example.com/parasite.jpg",
//       review: "A social satire thriller that leaves you on the edge of your seat.",
//       launchDate: "2019-05-30",
//       genre: "Drama, Thriller",
//       director: "Bong Joon Ho",
//       cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"]
//     },
//     {
//       name: "Interstellar",
//       title: "Interstellar",
//       language: "English",
//       imdbRating: 8.6,
//       photoLink: "https://example.com/interstellar.jpg",
//       review: "A visually breathtaking journey through space and time.",
//       launchDate: "2014-11-07",
//       genre: "Adventure, Drama, Sci-Fi",
//       director: "Christopher Nolan",
//       cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"]
//     },
//     {
//       name: "The Godfather",
//       title: "The Godfather",
//       language: "English",
//       imdbRating: 9.2,
//       photoLink: "https://example.com/godfather.jpg",
//       review: "A landmark in cinema, depicting the rise and fall of a crime family.",
//       launchDate: "1972-03-24",
//       genre: "Crime, Drama",
//       director: "Francis Ford Coppola",
//       cast: ["Marlon Brando", "Al Pacino", "James Caan"]
//     },
//     {
//       name: "Pulp Fiction",
//       title: "Pulp Fiction",
//       language: "English",
//       imdbRating: 8.9,
//       photoLink: "https://example.com/pulpfiction.jpg",
//       review: "A nonlinear narrative filled with dark humor and iconic dialogue.",
//       launchDate: "1994-10-14",
//       genre: "Crime, Drama",
//       director: "Quentin Tarantino",
//       cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"]
//     },
//     {
//       name: "Avengers: Endgame",
//       title: "Avengers: Endgame",
//       language: "English",
//       imdbRating: 8.4,
//       photoLink: "https://example.com/endgame.jpg",
//       review: "A spectacular culmination of the Marvel Cinematic Universe's saga.",
//       launchDate: "2019-04-26",
//       genre: "Action, Adventure, Drama",
//       director: "Anthony Russo, Joe Russo",
//       cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"]
//     },
//     {
//       name: "The Matrix",
//       title: "The Matrix",
//       language: "English",
//       imdbRating: 8.7,
//       photoLink: "https://example.com/matrix.jpg",
//       review: "A revolutionary sci-fi action film that changed the genre.",
//       launchDate: "1999-03-31",
//       genre: "Action, Sci-Fi",
//       director: "Lana Wachowski, Lilly Wachowski",
//       cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]
//     },
//     {
//       name: "Forrest Gump",
//       title: "Forrest Gump",
//       language: "English",
//       imdbRating: 8.8,
//       photoLink: "https://example.com/forrestgump.jpg",
//       review: "A heartwarming tale of a man who unknowingly influences key moments in history.",
//       launchDate: "1994-07-06",
//       genre: "Drama, Romance",
//       director: "Robert Zemeckis",
//       cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"]
//     },
//     {
//       name: "The Lion King",
//       title: "The Lion King",
//       language: "English",
//       imdbRating: 8.5,
//       photoLink: "https://example.com/lionking.jpg",
//       review: "A visually stunning animated classic with memorable songs.",
//       launchDate: "1994-06-24",
//       genre: "Animation, Adventure, Drama",
//       director: "Roger Allers, Rob Minkoff",
//       cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"]
//     },
//     // Additional 40 new movie objects
//     {
//       name: "The Avengers",
//       title: "The Avengers",
//       language: "English",
//       imdbRating: 8.1,
//       photoLink: "https://example.com/avengers.jpg",
//       review: "Marvel's superhero team-up film filled with action and humor.",
//       launchDate: "2012-05-04",
//       genre: "Action, Adventure, Sci-Fi",
//       director: "Joss Whedon",
//       cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"]
//     },
//     {
//       name: "Jurassic Park",
//       title: "Jurassic Park",
//       language: "English",
//       imdbRating: 8.1,
//       photoLink: "https://example.com/jurassicpark.jpg",
//       review: "A thrilling adventure with groundbreaking visual effects.",
//       launchDate: "1993-06-11",
//       genre: "Adventure, Sci-Fi",
//       director: "Steven Spielberg",
//       cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum"]
//     },
// ];
  
//   const webSeries = [
//     {
//       name: "Breaking Bad",
//       title: "Breaking Bad",
//       language: "English",
//       imdbRating: 9.5,
//       photoLink: "https://example.com/breakingbad.jpg",
//       review: "A gripping series with complex characters and intense drama.",
//       launchDate: "2008-01-20",
//       genre: "Crime, Drama, Thriller",
//       director: "Vince Gilligan",
//       cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"]
//     },
//     {
//       name: "Stranger Things",
//       title: "Stranger Things",
//       language: "English",
//       imdbRating: 8.7,
//       photoLink: "https://example.com/strangerthings.jpg",
//       review: "A nostalgic and thrilling series with a strong ensemble cast.",
//       launchDate: "2016-07-15",
//       genre: "Drama, Fantasy, Horror",
//       director: "The Duffer Brothers",
//       cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"]
//     },
//     {
//       name: "Game of Thrones",
//       title: "Game of Thrones",
//       language: "English",
//       imdbRating: 9.3,
//       photoLink: "https://example.com/got.jpg",
//       review: "An epic fantasy series filled with political intrigue, war, and dragons.",
//       launchDate: "2011-04-17",
//       genre: "Action, Adventure, Drama",
//       director: "David Benioff, D.B. Weiss",
//       cast: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"]
//     },
//     {
//       name: "The Mandalorian",
//       title: "The Mandalorian",
//       language: "English",
//       imdbRating: 8.8,
//       photoLink: "https://example.com/mandalorian.jpg",
//       review: "A captivating space adventure set in the Star Wars universe.",
//       launchDate: "2019-11-12",
//       genre: "Action, Adventure, Sci-Fi",
//       director: "Jon Favreau",
//       cast: ["Pedro Pascal", "Carl Weathers", "Gina Carano"]
//     },
//     {
//       name: "The Witcher",
//       title: "The Witcher",
//       language: "English",
//       imdbRating: 8.2,
//       photoLink: "https://example.com/witcher.jpg",
//       review: "A fantasy drama based on the beloved book series, filled with magic and monsters.",
//       launchDate: "2019-12-20",
//       genre: "Action, Adventure, Drama",
//       director: "Lauren Schmidt Hissrich",
//       cast: ["Henry Cavill", "Freya Allan", "Anya Chalotra"]
//     },
//     {
//       name: "Fleabag",
//       title: "Fleabag",
//       language: "English",
//       imdbRating: 8.7,
//       photoLink: "https://example.com/fleabag.jpg",
//       review: "A darkly comedic series with sharp writing and an unforgettable lead.",
//       launchDate: "2016-07-21",
//       genre: "Comedy, Drama",
//       director: "Phoebe Waller-Bridge",
//       cast: ["Phoebe Waller-Bridge", "Sian Clifford", "Olivia Colman"]
//     },
//     {
//       name: "The Crown",
//       title: "The Crown",
//       language: "English",
//       imdbRating: 8.7,
//       photoLink: "https://example.com/thecrown.jpg",
//       review: "A lavishly produced biographical drama about the reign of Queen Elizabeth II.",
//       launchDate: "2016-11-04",
//       genre: "Biography, Drama, History",
//       director: "Peter Morgan",
//       cast: ["Olivia Colman", "Claire Foy", "Matt Smith"]
//     },
//   ];
  
export const movies = [
    {
      id: 1,
      name: "The Dark Knight",
      title: "The Dark Knight",
      language: "English",
      imdbRating: 9.0,
      photoLink: "https://example.com/darkknight.jpg",
      review: "A masterful superhero film with intense performances.",
      launchDate: "2008-07-18",
      joner: "Action, Crime, Drama",
      director: "Christopher Nolan",
      cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"]
    },
    {
      id: 2,
      name: "Inception",
      title: "Inception",
      language: "English",
      imdbRating: 8.8,
      photoLink: "https://example.com/inception.jpg",
      review: "A visually stunning and intellectually stimulating heist film.",
      launchDate: "2010-07-16",
      joner: "Action, Adventure, Sci-Fi",
      director: "Christopher Nolan",
      cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"]
    },
    {
      id: 3,
      name: "Parasite",
      title: "Gisaengchung",
      language: "Korean",
      imdbRating: 8.6,
      photoLink: "https://example.com/parasite.jpg",
      review: "A social satire thriller that leaves you on the edge of your seat.",
      launchDate: "2019-05-30",
      joner: "Drama, Thriller",
      director: "Bong Joon Ho",
      cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"]
    },
    {
      id: 4,
      name: "Interstellar",
      title: "Interstellar",
      language: "English",
      imdbRating: 8.6,
      photoLink: "https://example.com/interstellar.jpg",
      review: "A visually breathtaking journey through space and time.",
      launchDate: "2014-11-07",
      joner: "Adventure, Drama, Sci-Fi",
      director: "Christopher Nolan",
      cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"]
    },
    {
      id: 5,
      name: "The Godfather",
      title: "The Godfather",
      language: "English",
      imdbRating: 9.2,
      photoLink: "https://example.com/godfather.jpg",
      review: "A landmark in cinema, depicting the rise and fall of a crime family.",
      launchDate: "1972-03-24",
      joner: "Crime, Drama",
      director: "Francis Ford Coppola",
      cast: ["Marlon Brando", "Al Pacino", "James Caan"]
    },
    // Additional movie entries...
    {
      id: 6,
      name: "Pulp Fiction",
      title: "Pulp Fiction",
      language: "English",
      imdbRating: 8.9,
      photoLink: "https://example.com/pulpfiction.jpg",
      review: "A nonlinear narrative filled with dark humor and iconic dialogue.",
      launchDate: "1994-10-14",
      joner: "Crime, Drama",
      director: "Quentin Tarantino",
      cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"]
    },
    {
      id: 7,
      name: "Avengers: Endgame",
      title: "Avengers: Endgame",
      language: "English",
      imdbRating: 8.4,
      photoLink: "https://example.com/endgame.jpg",
      review: "A spectacular culmination of the Marvel Cinematic Universe's saga.",
      launchDate: "2019-04-26",
      joner: "Action, Adventure, Drama",
      director: "Anthony Russo, Joe Russo",
      cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"]
    },
    {
      id: 8,
      name: "The Matrix",
      title: "The Matrix",
      language: "English",
      imdbRating: 8.7,
      photoLink: "https://example.com/matrix.jpg",
      review: "A revolutionary sci-fi action film that changed the genre.",
      launchDate: "1999-03-31",
      joner: "Action, Sci-Fi",
      director: "Lana Wachowski, Lilly Wachowski",
      cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]
    },
    // Additional 40 new movie objects...
    {
      id: 9,
      name: "Forrest Gump",
      title: "Forrest Gump",
      language: "English",
      imdbRating: 8.8,
      photoLink: "https://example.com/forrestgump.jpg",
      review: "A heartwarming tale of a man who unknowingly influences key moments in history.",
      launchDate: "1994-07-06",
      joner: "Drama, Romance",
      director: "Robert Zemeckis",
      cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"]
    },
    {
      id: 10,
      name: "The Lion King",
      title: "The Lion King",
      language: "English",
      imdbRating: 8.5,
      photoLink: "https://example.com/lionking.jpg",
      review: "A visually stunning animated classic with memorable songs.",
      launchDate: "1994-06-24",
      joner: "Animation, Adventure, Drama",
      director: "Roger Allers, Rob Minkoff",
      cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"]
    }
  ];
  
  
  const bollywoodMovies = [
    "Sholay",
    "Dilwale Dulhania Le Jayenge",
    "3 Idiots",
    "Kabhi Khushi Kabhie Gham",
    "Dangal",
    "PK",
    "Mughal-e-Azam",
    "Chennai Express",
    "Bahubali",
    "Padmaavat",
    "Kuch Kuch Hota Hai",
    "Gully Boy",
    "Lagaan",
    "Raazi",
    "Andhadhun",
    "Bajrangi Bhaijaan",
    "Queen",
    "Pyaasa",
    "Swades",
    "Barfi!",
    "Golmaal",
    "Gangs of Wasseypur",
    "Rockstar",
    "Don",
    "Zindagi Na Milegi Dobara",
    "Student of the Year",
    "Om Shanti Om",
    "Tamasha",
    "Piku",
    "Jab We Met",
    "Article 15",
    "Deewaar",
    "Sanju",
    "Koi Mil Gaya",
    "Veer-Zaara",
    "Badla",
    "Bhoot",
    "Kahaani",
    "Kalank",
    "Housefull",
    "Race",
    "Hum Aapke Hain Koun..!",
    "Main Hoon Na",
    "Dil Chahta Hai",
    "Dhoom",
    "Badlapur",
    "Gunda",
    "Karthik Calling Karthik",
    "Bhoot Police",
    "Kaabil",
    "Bareilly Ki Barfi",
    "Gold",
    "Secret Superstar",
    "Stree",
    "Kabir Singh",
    "War",
    "Thappad",
    "Baaghi",
    "Mimi",
    "Simmba",
    "Kesari",
    "Ek Tha Tiger",
    "Ghajini",
    "Jolly LLB",
    "Chhichhore",
    "M.S. Dhoni: The Untold Story",
    "Rang De Basanti",
    "Gully Boy",
    "Heropanti",
    "Dostana",
    "Drishyam",
    "Krrish",
    "Super 30",
    "Sultan",
    "Kaagaz",
    "Dum Laga Ke Haisha",
    "Shubh Mangal Saavdhan",
    "Batla House",
    "Airlift",
    "Lootera",
    "Holiday",
    "Fan",
    "Fukrey",
    "Masaan",
    "Talvar",
    "Baahubali 2: The Conclusion",
    "Kahaani 2",
    "Shahid",
    "Neerja",
    "Baby",
    "Hindi Medium",
    "Chupke Chupke",
    "Raat Akeli Hai",
    "Raees",
    "Toilet: Ek Prem Katha",
    "Raajneeti",
    "Udaan",
    "Black Friday",
    "Dev D",
    "Jannat",
    "Murder",
    "Satyameva Jayate",
    "Ram-Leela",
    "Race 2",
    "Student of the Year 2",
    "Dishoom",
    "Action Replayy",
    "Bang Bang!",
    "Housefull 3",
    "Partner",
    "Heyy Babyy",
    "Murder 2",
    "Baazigar",
    "Don 2",
    "Maine Pyaar Kiya",
    "Singham",
    "Zanjeer",
    "Gangaajal",
    "Mr. India",
    "Mohra",
    "Race 3",
    "Gabbar Is Back",
    "Shivaay",
    "Bodyguard",
    "Rustom",
    "Kaante",
    "Fanaa",
    "Ajnabee",
    "Saaho",
    "Shootout at Lokhandwala",
    "Once Upon a Time in Mumbaai",
    "Desi Boyz",
    "Tees Maar Khan",
    "Commando",
    "Wanted",
    "Rowdy Rathore",
    "Tanhaji",
    "Sadak",
    "Housefull 2",
    "Golmaal Returns",
    "Judwaa",
    "Baazi",
    "Agent Vinod",
    "Mission Mangal",
    "Pati Patni Aur Woh",
    "Jab Tak Hai Jaan",
    "Manikarnika",
    "Mardaani",
    "Dabangg",
    "Ra. One",
    "Hate Story",
    "Dil Toh Pagal Hai",
    "Happy New Year",
    "Dhadak",
    "Kal Ho Naa Ho",
    "Love Aaj Kal",
    "Satyagraha",
    "Zero",
    "Jism",
    "Dostana 2",
    "Chori Chori Chupke Chupke",
    "Tum Mile",
    "Drive",
    "Veere Di Wedding",
    "Luck",
    "Pari",
    "Ghanchakkar",
    "Masti",
    "Grand Masti",
    "Great Grand Masti",
    "Bol Bachchan",
    "Welcome",
    "Singh is Kinng",
    "Kaminey",
    "Tevar",
    "Total Dhamaal",
    "Force",
    "Kick",
    "Dil Se",
    "Dilwale",
    "The Sky Is Pink",
    "Hero",
    "Badhaai Ho",
    "Chennai Express",
    "Shuddh Desi Romance",
    "Malang",
    "Sonu Ke Titu Ki Sweety",
    "Dhoom 2",
    "Fida",
    "Aashiqui 2",
    "Yaadein",
    "Hum Tum",
    "Bunty Aur Babli",
    "Ladies vs Ricky Bahl",
    "Band Baaja Baaraat",
    "Khoobsurat",
    "Laal Kaptaan",
    "Panga",
    "Love Story 2050",
  ];
  
  const webSeries = [
    "Sacred Games",
    "Mirzapur",
    "The Family Man",
    "Paatal Lok",
    "Delhi Crime",
    "Made in Heaven",
    "Breathe",
    "Inside Edge",
    "Criminal Justice",
    "Special OPS",
    "Kota Factory",
    "Aarya",
    "Asur",
    "Bard of Blood",
    "Rangbaaz",
    "Four More Shots Please!",
    "Hostages",
    "Betaal",
    "She",
    "Little Things",
    "Yeh Meri Family",
    "TVF Pitchers",
    "TVF Tripling",
    "Gullak",
    "College Romance",
    "Aspirants",
    "Engineering Girls",
    "Jamtara",
    "Undekhi",
    "Grahan",
    "Mismatched",
    "The Gone Game",
    "Scam 1992",
    "Bandish Bandits",
    "Aashram",
    "Out of Love",
    "The Great Indian Dysfunctional Family",
    "Leila",
    "Tandav",
    "Broken But Beautiful",
    "Avrodh",
    "The Raikar Case",
    "The Final Call",
    "Mind The Malhotras",
    "Bombay Begums",
    "Bang Baaja Baaraat",
    "Rasbhari",
    "Selection Day",
    "Breathe: Into the Shadows",
    "Crackdown",
    "Illegal",
    "The Chargesheet",
    "Love, Lust & Confusion",
    "Operation MBBS",
    "Panchayat",
    "Hostel Daze",
    "Rangbaaz Phirse",
    "Kehne Ko Humsafar Hain",
    "Code M",
    "Dark 7 White",
    "The Verdict – State vs Nanavati",
    "Abhay",
    "Ek Thi Begum",
    "Damaged",
    "Madhuri Talkies",
    "High",
    "Kaafir",
    "Flesh",
    "Poison",
    "Hello Mini",
    "Apharan",
    "Cold Lassi Aur Chicken Masala",
    "Fixerr",
    "Haq Se",
    "Naxalbari",
    "Mannphodganj Ki Binny",
    "Marzi",
    "Ramyug",
    "Kaali",
    "Maaya",
    "Gandii Baat",
    "Comicstaan",
    "Karenjit Kaur",
    "Sons of the Soil",
    "The Test Case",
    "It Happened in Hong Kong",
    "Love Bites",
    "Masaba Masaba",
    "Twisted",
    "Pavitra Rishta: Its Never Too Late",
    "Dev DD",
    "Thinkistan",
    "Hadh",
    "One Mic Stand",
    "The Married Woman",
    "Bekaaboo",
    "TSP's Zeroes",
    "Addham",
    "MX TakaTak Fame House",
    "The Holiday",
    "Hum Tum and Them",
    "Queen",
    "Ek Jhooti Love Story",
    "Humorously Yours",
    "The Office",
    "Dil Bekaraar",
    "Bhonsle",
    "Typewriter",
    "City of Dreams",
    "The Forgotten Army",
    "Hundred",
    "Chacha Vidhayak Hain Humare",
    "Tripling",
    "Fuh Se Fantasy",
    "Mission Over Mars",
    "Illegal - Justice, Out of Order",
    "Ragini MMS: Returns",
    "Nivaran",
    "Skyfire",
    "MTV Nishedh",
    "Unpaused",
    "Khwabon Ke Parindey",
    "Home",
    "Flip",
    "Fourplay",
    "Tere Liye Bro",
    "Thinkistan Season 2",
    "The Reunion",
    "The Sholay Girl",
    "The Insiders",
    "Smoke",
    "Shockers",
    "Hey Prabhu",
    "Shaitaan Haveli",
    "Bose: Dead/Alive",
    "Test Drive",
    "Untag",
    "Ready 2 Mingle",
    "All About Section 377",
    "Shaadi Boys",
    "Official Bhootiyagiri",
    "Asur: Welcome to Your Dark Side",
    "Faceless",
    "Kaalchakra",
    "14 Phere",
    "Broken But Beautiful 2",
    "Nasha",
    "TVF Inmates",
    "Cubicles",
    "The Great Weddings of Munnes",
    "Please Find Attached",
    "Tandav 2",
    "Love Ok Please",
    "Runaway Lugaai",
    "Sunflower",
    "Lootcase",
    "The Aam Aadmi Family",
    "Shaadi Fit",
    "Raja Rasoi Aur Anya Kahaniyan",
    "Baahubali: Before the Beginning",
    "Nirvana Inn",
    "Posham Pa",
    "The Big Day",
    "Yeh Kaali Kaali Ankhein",
    "Hello Jee",
    "The Casino",
    "Inspector Avinash",
    "Nail Polish",
    "Indori Ishq",
    "Pyaar Ka Punchnama",
    "Jeet Ki Zid",
    "Scam 2003",
    "F.A.T.H.E.R.S.",
    "The Whistleblower",
    "Who’s Your Daddy",
    "Mind Games",
    "Illegal 2",
    "The Viral Fever Sketch",
    "LSD - Love, Scandal & Doctors",
    "Ramyug 2",
    "Tryst With Destiny",
    "Karrle Tu Bhi Mohabbat",
    "Girls Hostel",
    "Runaways",
    "Mumbai Diaries",
    "Bombay High",
    "Paranormal",
    "Black Widows",
    "Bekaaboo 2",
    "Hello Mini 3",
    "The Billionaire Rapper",
    "The D Company",
    "You’re My Crush",
    "Cheesecake",
  ];
  
  export { bollywoodMovies, webSeries };
  