
  
  
  const bollywoodMovies = [
    "Sholay",
    "Dilwale Dulhania Le Jayenge",
    "3 Idiots",
    "Kabhi Khushi Kabhie Gham",
    "Dangal",
    "PK",
    "Mughal-e-Azam",
    "Chennai Express",
    "Bahubali",
    "Padmaavat",
    "Kuch Kuch Hota Hai",
    "Gully Boy",
    "Lagaan",
    "Raazi",
    "Andhadhun",
    "Bajrangi Bhaijaan",
    "Queen",
    "Pyaasa",
    "Swades",
    "Barfi!",
    "Golmaal",
    "Gangs of Wasseypur",
    "Rockstar",
    "Don",
    "Zindagi Na Milegi Dobara",
    "Student of the Year",
    "Om Shanti Om",
    "Tamasha",
    "Piku",
    "Jab We Met",
    "Article 15",
    "Deewaar",
    "Sanju",
    "Koi Mil Gaya",
    "Veer-Zaara",
    "Badla",
    "Bhoot",
    "Kahaani",
    "Kalank",
    "Housefull",
    "Race",
    "Hum Aapke Hain Koun..!",
    "Main Hoon Na",
    "Dil Chahta Hai",
    "Dhoom",
    "Badlapur",
    "Gunda",
    "Karthik Calling Karthik",
    "Bhoot Police",
    "Kaabil",
    "Bareilly Ki Barfi",
    "Gold",
    "Secret Superstar",
    "Stree",
    "Kabir Singh",
    "War",
    "Thappad",
    "Baaghi",
    "Mimi",
    "Simmba",
    "Kesari",
    "Ek Tha Tiger",
    "Ghajini",
    "Jolly LLB",
    "Chhichhore",
    "M.S. Dhoni: The Untold Story",
    "Rang De Basanti",
    "Gully Boy",
    "Heropanti",
    "Dostana",
    "Drishyam",
    "Krrish",
    "Super 30",
    "Sultan",
    "Kaagaz",
    "Dum Laga Ke Haisha",
    "Shubh Mangal Saavdhan",
    "Batla House",
    "Airlift",
    "Lootera",
    "Holiday",
    "Fan",
    "Fukrey",
    "Masaan",
    "Talvar",
    "Baahubali 2: The Conclusion",
    "Kahaani 2",
    "Shahid",
    "Neerja",
    "Baby",
    "Hindi Medium",
    "Chupke Chupke",
    "Raat Akeli Hai",
    "Raees",
    "Toilet: Ek Prem Katha",
    "Raajneeti",
    "Udaan",
    "Black Friday",
    "Dev D",
    "Jannat",
    "Murder",
    "Satyameva Jayate",
    "Ram-Leela",
    "Race 2",
    "Student of the Year 2",
    "Dishoom",
    "Action Replayy",
    "Bang Bang!",
    "Housefull 3",
    "Partner",
    "Heyy Babyy",
    "Murder 2",
    "Baazigar",
    "Don 2",
    "Maine Pyaar Kiya",
    "Singham",
    "Zanjeer",
    "Gangaajal",
    "Mr. India",
    "Mohra",
    "Race 3",
    "Gabbar Is Back",
    "Shivaay",
    "Bodyguard",
    "Rustom",
    "Kaante",
    "Fanaa",
    "Ajnabee",
    "Saaho",
    "Shootout at Lokhandwala",
    "Once Upon a Time in Mumbaai",
    "Desi Boyz",
    "Tees Maar Khan",
    "Commando",
    "Wanted",
    "Rowdy Rathore",
    "Tanhaji",
    "Sadak",
    "Housefull 2",
    "Golmaal Returns",
    "Judwaa",
    "Baazi",
    "Agent Vinod",
    "Mission Mangal",
    "Pati Patni Aur Woh",
    "Jab Tak Hai Jaan",
    "Manikarnika",
    "Mardaani",
    "Dabangg",
    "Ra. One",
    "Hate Story",
    "Dil Toh Pagal Hai",
    "Happy New Year",
    "Dhadak",
    "Kal Ho Naa Ho",
    "Love Aaj Kal",
    "Satyagraha",
    "Zero",
    "Jism",
    "Dostana 2",
    "Chori Chori Chupke Chupke",
    "Tum Mile",
    "Drive",
    "Veere Di Wedding",
    "Luck",
    "Pari",
    "Ghanchakkar",
    "Masti",
    "Grand Masti",
    "Great Grand Masti",
    "Bol Bachchan",
    "Welcome",
    "Singh is Kinng",
    "Kaminey",
    "Tevar",
    "Total Dhamaal",
    "Force",
    "Kick",
    "Dil Se",
    "Dilwale",
    "The Sky Is Pink",
    "Hero",
    "Badhaai Ho",
    "Chennai Express",
    "Shuddh Desi Romance",
    "Malang",
    "Sonu Ke Titu Ki Sweety",
    "Dhoom 2",
    "Fida",
    "Aashiqui 2",
    "Yaadein",
    "Hum Tum",
    "Bunty Aur Babli",
    "Ladies vs Ricky Bahl",
    "Band Baaja Baaraat",
    "Khoobsurat",
    "Laal Kaptaan",
    "Panga",
    "Love Story 2050",
  ];
  
  const webSeries = [
    "Sacred Games",
    "Mirzapur",
    "The Family Man",
    "Paatal Lok",
    "Delhi Crime",
    "Made in Heaven",
    "Breathe",
    "Inside Edge",
    "Criminal Justice",
    "Special OPS",
    "Kota Factory",
    "Aarya",
    "Asur",
    "Bard of Blood",
    "Rangbaaz",
    "Four More Shots Please!",
    "Hostages",
    "Betaal",
    "She",
    "Little Things",
    "Yeh Meri Family",
    "TVF Pitchers",
    "TVF Tripling",
    "Gullak",
    "College Romance",
    "Aspirants",
    "Engineering Girls",
    "Jamtara",
    "Undekhi",
    "Grahan",
    "Mismatched",
    "The Gone Game",
    "Scam 1992",
    "Bandish Bandits",
    "Aashram",
    "Out of Love",
    "The Great Indian Dysfunctional Family",
    "Leila",
    "Tandav",
    "Broken But Beautiful",
    "Avrodh",
    "The Raikar Case",
    "The Final Call",
    "Mind The Malhotras",
    "Bombay Begums",
    "Bang Baaja Baaraat",
    "Rasbhari",
    "Selection Day",
    "Breathe: Into the Shadows",
    "Crackdown",
    "Illegal",
    "The Chargesheet",
    "Love, Lust & Confusion",
    "Operation MBBS",
    "Panchayat",
    "Hostel Daze",
    "Rangbaaz Phirse",
    "Kehne Ko Humsafar Hain",
    "Code M",
    "Dark 7 White",
    "The Verdict – State vs Nanavati",
    "Abhay",
    "Ek Thi Begum",
    "Damaged",
    "Madhuri Talkies",
    "High",
    "Kaafir",
    "Flesh",
    "Poison",
    "Hello Mini",
    "Apharan",
    "Cold Lassi Aur Chicken Masala",
    "Fixerr",
    "Haq Se",
    "Naxalbari",
    "Mannphodganj Ki Binny",
    "Marzi",
    "Ramyug",
    "Kaali",
    "Maaya",
    "Gandii Baat",
    "Comicstaan",
    "Karenjit Kaur",
    "Sons of the Soil",
    "The Test Case",
    "It Happened in Hong Kong",
    "Love Bites",
    "Masaba Masaba",
    "Twisted",
    "Pavitra Rishta: Its Never Too Late",
    "Dev DD",
    "Thinkistan",
    "Hadh",
    "One Mic Stand",
    "The Married Woman",
    "Bekaaboo",
    "TSP's Zeroes",
    "Addham",
    "MX TakaTak Fame House",
    "The Holiday",
    "Hum Tum and Them",
    "Queen",
    "Ek Jhooti Love Story",
    "Humorously Yours",
    "The Office",
    "Dil Bekaraar",
    "Bhonsle",
    "Typewriter",
    "City of Dreams",
    "The Forgotten Army",
    "Hundred",
    "Chacha Vidhayak Hain Humare",
    "Tripling",
    "Fuh Se Fantasy",
    "Mission Over Mars",
    "Illegal - Justice, Out of Order",
    "Ragini MMS: Returns",
    "Nivaran",
    "Skyfire",
    "MTV Nishedh",
    "Unpaused",
    "Khwabon Ke Parindey",
    "Home",
    "Flip",
    "Fourplay",
    "Tere Liye Bro",
    "Thinkistan Season 2",
    "The Reunion",
    "The Sholay Girl",
    "The Insiders",
    "Smoke",
    "Shockers",
    "Hey Prabhu",
    "Shaitaan Haveli",
    "Bose: Dead/Alive",
    "Test Drive",
    "Untag",
    "Ready 2 Mingle",
    "All About Section 377",
    "Shaadi Boys",
    "Official Bhootiyagiri",
    "Asur: Welcome to Your Dark Side",
    "Faceless",
    "Kaalchakra",
    "14 Phere",
    "Broken But Beautiful 2",
    "Nasha",
    "TVF Inmates",
    "Cubicles",
    "The Great Weddings of Munnes",
    "Please Find Attached",
    "Tandav 2",
    "Love Ok Please",
    "Runaway Lugaai",
    "Sunflower",
    "Lootcase",
    "The Aam Aadmi Family",
    "Shaadi Fit",
    "Raja Rasoi Aur Anya Kahaniyan",
    "Baahubali: Before the Beginning",
    "Nirvana Inn",
    "Posham Pa",
    "The Big Day",
    "Yeh Kaali Kaali Ankhein",
    "Hello Jee",
    "The Casino",
    "Inspector Avinash",
    "Nail Polish",
    "Indori Ishq",
    "Pyaar Ka Punchnama",
    "Jeet Ki Zid",
    "Scam 2003",
    "F.A.T.H.E.R.S.",
    "The Whistleblower",
    "Who’s Your Daddy",
    "Mind Games",
    "Illegal 2",
    "The Viral Fever Sketch",
    "LSD - Love, Scandal & Doctors",
    "Ramyug 2",
    "Tryst With Destiny",
    "Karrle Tu Bhi Mohabbat",
    "Girls Hostel",
    "Runaways",
    "Mumbai Diaries",
    "Bombay High",
    "Paranormal",
    "Black Widows",
    "Bekaaboo 2",
    "Hello Mini 3",
    "The Billionaire Rapper",
    "The D Company",
    "You’re My Crush",
    "Cheesecake",
  ];
  
  export { bollywoodMovies, webSeries };
  